// OmpLoweringOps.cpp
//
// Provides:
//   - Dialect constructor / initialize()  (using generated .inc files)
//   - ConstructOp::build()
//   - ConstructOp::verify()
//
// Everything else (attribute storage, get(), accessors, op boilerplate) is
// generated by mlir-tblgen and pulled in via the .inc files.

#include "OmpLowering/IR/OmpLoweringOps.h"

#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/OpImplementation.h"
#include "llvm/ADT/TypeSwitch.h"

using namespace mlir;
using namespace mlir::omp_lower;

// ---------------------------------------------------------------------------
// Dialect
// ---------------------------------------------------------------------------

// Generated dialect definition (initialize() body, type/attr registration).
#include "OmpLowering/IR/OmpLoweringOps.dialect.cpp.inc"

void OmpLoweringDialect::initialize() {
  addOperations<
#define GET_OP_LIST
#include "OmpLowering/IR/OmpLoweringOps.cpp.inc"
  >();
  addAttributes<
#define GET_ATTRDEF_LIST
#include "OmpLowering/IR/OmpLoweringAttrs.cpp.inc"
  >();
}

// ---------------------------------------------------------------------------
// Attribute definitions (storage, get(), accessors, printer/parser).
// All generated – we just include the .inc.
// ---------------------------------------------------------------------------

#define GET_ATTRDEF_CLASSES
#include "OmpLowering/IR/OmpLoweringAttrs.cpp.inc"

// ---------------------------------------------------------------------------
// Op definitions (boilerplate, default builders, print/parse).
// ---------------------------------------------------------------------------

#define GET_OP_CLASSES
#include "OmpLowering/IR/OmpLoweringOps.cpp.inc"

// ---------------------------------------------------------------------------
// ConstructOp
// ---------------------------------------------------------------------------

LogicalResult ConstructOp::verify() {
  auto rt = getRuntime();
  if (rt != "iomp" && rt != "libgomp" && rt != "pmsis")
    return (*this)->emitOpError("unknown runtime '")
           << rt << "'; expected 'iomp', 'libgomp' or 'pmsis'";

  auto checkBlock = [&](ArrayAttr block, llvm::StringRef blockName)
      -> LogicalResult {
    if (!block) return success();
    for (auto attr : block) {
      if (!llvm::isa<PlanCallAttr>(attr) && !llvm::isa<PlanEmitAttr>(attr))
        return (*this)->emitOpError("block '") << blockName
               << "' contains unexpected attribute: " << attr;
    }
    return success();
  };

  if (failed(checkBlock(getPre(),    "pre")))    return failure();
  if (failed(checkBlock(getInvoke(), "invoke"))) return failure();
  if (failed(checkBlock(getPost(),   "post")))   return failure();
  return success();
}
