// OmpLoweringOps.h
//
// All class declarations are generated by mlir-tblgen from OmpLoweringOps.td.
// This header includes the generated .inc files in the required order.
//
// Generated files and the tblgen flags that produce them:
//   OmpLoweringOps.dialect.h.inc   (-gen-dialect-decls)
//   OmpLoweringAttrs.h.inc         (-gen-attrdef-decls)
//   OmpLoweringOps.h.inc           (-gen-op-decls)

#pragma once

#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/OperationSupport.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
// BytecodeOpInterface is referenced by the generated .inc: the op attributes
// are stored as properties, which are read and written through it.
#include "mlir/Bytecode/BytecodeOpInterface.h"

// Step 1: dialect class declaration.
#include "OmpLowering/IR/OmpLoweringOps.dialect.h.inc"

// Step 2: attribute class declarations (PlanCallAttr, PlanEmitAttr).
#define GET_ATTRDEF_CLASSES
#include "OmpLowering/IR/OmpLoweringAttrs.h.inc"

// Step 3: op class declarations (ConstructOp).
#define GET_OP_CLASSES
#include "OmpLowering/IR/OmpLoweringOps.h.inc"
